# Schema reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

variables:
  isMasterBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/ci_cd')]
  publishArtifactName: 'mantasflowers-frontend'
  projectPathPrefix: './front'
  __Githash: $(Build.SourceVersion)

pool:
  vmImage: ubuntu-18.04

# Run on every push
# trigger:

# Run on every pull request
# pr:


steps:
  - task: NodeTool@0
    displayName: install node tool
    inputs:
      versionSpec: '14.x'
      checkLatest: false

  - script: npm install
    displayName: npm install
    workingDirectory: $(projectPathPrefix)/

  - script: npm run test -- --watchAll=false --passWithNoTests
    displayName: npm run test
    # we can disable this if we won't have any tests :)
    enabled: true
    workingDirectory: $(projectPathPrefix)/

  - script: npm run build
    displayName: npm run build
    workingDirectory: $(projectPathPrefix)/

  - task: ArchiveFiles@2
    displayName: archive build files
    condition: and(succeeded(), eq(variables.isMasterBranch, true))
    inputs:
      rootFolderOrFile: './front/build'
      # might need to change below to false
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(publishArtifactName).zip'
      replaceExistingArchive: false

  # - task: CopyFiles@2
  #   condition: and(succeeded(), eq(variables.isMasterBranch, true))
  #   displayName: copy build files
  #   inputs:
  #     SourceFolder: $(projectPathPrefix)
  #     Contents: 'build/**'
  #     TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables.isMasterBranch, true))
    displayName: azure artifacts publish
    inputs:
      # might need to change to $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: $(publishArtifactName)


# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '14.x'
#     checkLatest: false

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'
#   workingDirectory: $(projectPathPrefix)